# Generated by Django 4.0.4 on 2022-05-17 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_choice_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(default=None, max_length=100)),
                ('jenis_upload', models.CharField(choices=[('buku', 'Kecil'), ('jurnal', 'Medium')], default=None, max_length=100, null=True)),
                ('tahun_terbit', models.IntegerField(default=2017)),
            ],
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='gambar/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='home.dataupload')),
            ],
        ),
    ]
