# Generated by Django 4.0.4 on 2022-05-17 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='post',
        ),
        migrations.DeleteModel(
            name='DataUpload',
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
